CREATE DATABASE IF NOT EXISTS mybatis;

USE mybatis;

CREATE TABLE IF NOT EXISTS dept(
    did INT(11) NOT NULL AUTO_INCREMENT,
    dname VARCHAR(50) NOT NULL,
    PRIMARY KEY(did)
)ENGINE = INNODB DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS user(
    uid INT(11) NOT NULL AUTO_INCREMENT,
    uname VARCHAR(50) NOT NULL,
    did INT(11),
    PRIMARY KEY(uid),
    FOREIGN KEY(did) REFERENCES dept(did)
)ENGINE = INNODB DEFAULT CHARSET = utf8;